### PR TITLE
Preliminary VCF support

### PR DESCRIPTION
**Pull request by teepean**
Getting snipsa to load VCFs was easy but I could not figure out how to detect a correct build.

### CODE REVIEW

**Comment by alinja** [comment]
Build could probably be autodetected based on the contig names "chrY" vs "Y"

**Comment by teepean** [comment]
Problem is that both hg19 and hg38 use chr prefix.

**Comment by alinja** [comment]
Hg19 and hg37 use same positions, their difference is in the annotations. I don't think there is need to differentiate between them.

**Comment by teepean** [comment]
Marker names are the same but positions differ. Random example:

`{'m': 'FGC14166', 'mall': 'FGC14166, Z4939', 'g': 'N1a1a1a1a1a2a', 'rs': '', 'b37': '21333667', 'b38': '19171781', 'p': 'T', 'b36': '19793055'}`

**Comment by alinja** [comment]
Sorry, I thought you meant hg19 and hg37. I need to check if I actually have any samples of hg19 anywhere.

**Comment by alinja** [comment]
I found two hg19 samples and neither uses chrY naming.

**Comment by teepean** [comment]
Maybe the build could be entered manually when specifying that the input is a VCF?

**Pull request closed without merging**
